version: "3.2"

services:
  proxy:
    image: golang:1.12
    command: ["bash", "-c", "cd /app && go run main.go -bind 0.0.0.0:5432 -dest postgres:5432"]
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine

  pgbench:
    image: postgres:11-alpine
    command: ["bash", "-c", "
      pgbench -i -s 5 -h proxy -U postgres && \
      echo && \
      pgbench -T 10 -M simple -h proxy -U postgres && \
      echo && \
      pgbench -T 10 -M extended -h proxy -U postgres && \
      echo && \
      pgbench -T 10 -M prepared -h proxy -U postgres
    "]
    depends_on:
      - proxy